
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      # 1. Montamos la CARPETA completa en una ruta temporal dentro del contenedor
      - C:\RoclandConfig:C:\external_secrets:ro
    # 2. Truco: Copiamos el archivo y luego arrancamos la app
    entrypoint: 
      - cmd
      - /c
      - copy C:\external_secrets\appsettings.Secrets.json C:\app\appsettings.Secrets.json && dotnet RoclandAccesoControl.Web.dll
